AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude: 
    - "bin/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "config/**/*"
    - "app/mailers/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'let']

Metrics/ClassLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
