default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: fraud-pg
  username: postgres
  password: postgres

development:
  <<: *default
  database: fraud_development

test:
  <<: *default
  database: fraud_test

production:
  <<: *default
  database: fraud_production
  username: fraud
  password: <%= ENV["FRAUD_DATABASE_PASSWORD"] %>
